/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import DAO.EdicaoFaturaGipDAO;
import DTO.EdicaoFaturaGipDTO;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author jateixeira
 */
public class TelaEdicaoFatura extends javax.swing.JFrame {

    /**
     * Creates new form TelaEdição
     */
    public TelaEdicaoFatura() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        VoltarBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        EditarTxt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        EditarTable = new javax.swing.JTable();
        ApagarTxt = new javax.swing.JButton();
        InstalacaoTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        BuscarTxt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        VoltarBtn.setText("VOLTAR");
        VoltarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VoltarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("EDITAR INSTALAÇÕES");

        EditarTxt.setText("EDITAR");
        EditarTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EditarTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarTxtActionPerformed(evt);
            }
        });

        EditarTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código barras", "Instalação", "Carga Lev.", "Medidor Inst.", "Rua", "Numero", "Bairro", "Tipos", "Barras Red.", "Unidade"
            }
        ));
        jScrollPane1.setViewportView(EditarTable);

        ApagarTxt.setText("APAGAR");
        ApagarTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel2.setText("Instalação:");

        BuscarTxt.setText("BUSCAR");
        BuscarTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BuscarTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(324, 324, 324)
                        .addComponent(jLabel2)
                        .addGap(60, 60, 60)
                        .addComponent(InstalacaoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(BuscarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(453, 453, 453)
                        .addComponent(jLabel1)))
                .addGap(0, 337, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(VoltarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(340, 340, 340)
                        .addComponent(EditarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ApagarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(InstalacaoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BuscarTxt))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditarTxt)
                    .addComponent(ApagarTxt)
                    .addComponent(VoltarBtn))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VoltarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarBtnActionPerformed
       TelaConsultarFaturas telaConsultarFatura = new TelaConsultarFaturas();
       telaConsultarFatura.setVisible(true);
       
       this.dispose();
    }//GEN-LAST:event_VoltarBtnActionPerformed

    private void EditarTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarTxtActionPerformed
        try{
            Atualizar();
        }
        catch(Exception erro){
            JOptionPane.showMessageDialog(null, "deu erro");
        }
    }//GEN-LAST:event_EditarTxtActionPerformed

    private void BuscarTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarTxtActionPerformed
         try{
            listarValores();
        }
        catch (Exception erro){
            JOptionPane.showMessageDialog(null, "não há registros identificados" + erro);
        }
    }//GEN-LAST:event_BuscarTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEdicaoFatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEdicaoFatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEdicaoFatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEdicaoFatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEdicaoFatura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ApagarTxt;
    private javax.swing.JButton BuscarTxt;
    private javax.swing.JTable EditarTable;
    private javax.swing.JButton EditarTxt;
    private javax.swing.JTextField InstalacaoTxt;
    private javax.swing.JButton VoltarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

private void listarValores() {
        try {
            EdicaoFaturaGipDAO edicaogipdao = new EdicaoFaturaGipDAO();
             
            DefaultTableModel model = (DefaultTableModel) EditarTable.getModel();
            model.setNumRows(0);
            
            String inst = InstalacaoTxt.getText();
            
            
            List<EdicaoFaturaGipDTO> lista = edicaogipdao.EdicaoFatura(inst);
                    
                 
                for(int i = 0; i < lista.size(); i ++){
                    model.addRow(new Object[]{
                        
                        lista.get(i ).getCodigoBarras_faturanova(),
                        lista.get(i).getInstalacao_faturanova(),
                        lista.get(i).getCargaLevantada_faturanova(),
                        lista.get(i).getMedidorInstalacao_faturanova(),
                        lista.get(i).getRua_faturanova(),
                        lista.get(i).getNumero_faturanova(),
                        lista.get(i).getBairro_faturanova(),
                        lista.get(i).getTipos_faturanova(),
                        lista.get(i).getCodBarrasRed_faturanova(),
                        lista.get(i).getUnidade_faturanova(),
                        /*lista.get(i).getCodigoBarrasCon_cadastroConsumoFatura(),
                        lista.get(i).getValor_cadastroConsumoFatura(),
                        lista.get(i).getKw_cadastroConsumoFatura(),
                        lista.get(i).getMesVencimento_cadastroConsumoFatura(),
                        lista.get(i).getMesReferente_cadastroConsumoFatura(),
                        lista.get(i).getDataCadastro_cadastroConsumoFatura(),
                        lista.get(i).getAno_cadastroConsumoFatura(),
                        lista.get(i).getCodBarrasRed_cadastroConsumoFatura()*/
                    });
                }
            
            
            
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null,"listarValores" + erro);
        }
    }
 

    private List<EdicaoFaturaGipDTO> getValoresOriginais() {
        List<EdicaoFaturaGipDTO> valoresOriginais = new ArrayList<>();

        try {
            DefaultTableModel model = (DefaultTableModel) EditarTable.getModel();
            int numRows = model.getRowCount();

            for (int i = 0; i < numRows; i++) {
                EdicaoFaturaGipDTO edicaoGipDTO = new EdicaoFaturaGipDTO();

                edicaoGipDTO.setCodigoBarras_faturanova(model.getValueAt(i, 0).toString());
                edicaoGipDTO.setInstalacao_faturanova(model.getValueAt(i, 1).toString());
                edicaoGipDTO.setCargaLevantada_faturanova(model.getValueAt(i, 2).toString());
                edicaoGipDTO.setMedidorInstalacao_faturanova(model.getValueAt(i, 3).toString());
                edicaoGipDTO.setRua_faturanova(model.getValueAt(i, 4).toString());
                edicaoGipDTO.setNumero_faturanova(model.getValueAt(i, 5).toString());
                edicaoGipDTO.setBairro_faturanova(model.getValueAt(i, 6).toString());
                edicaoGipDTO.setTipos_faturanova(model.getValueAt(i, 7).toString());
                edicaoGipDTO.setCodBarrasRed_faturanova(model.getValueAt(i, 8).toString());
                edicaoGipDTO.setUnidade_faturanova(model.getValueAt(i, 9).toString());
               
                valoresOriginais.add(edicaoGipDTO);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao obter valores originais: " + e.getMessage());
        }

        return valoresOriginais;
    }

    private boolean houveAlteracoes(List<EdicaoFaturaGipDTO> valoresOriginais) {
        DefaultTableModel model = (DefaultTableModel) EditarTable.getModel();
        int numRows = model.getRowCount();

        for (int i = 0; i < numRows; i++) {
           EdicaoFaturaGipDTO edicaoGipDTO = new EdicaoFaturaGipDTO();

                edicaoGipDTO.setCodigoBarras_faturanova(model.getValueAt(i, 0).toString());
                edicaoGipDTO.setInstalacao_faturanova(model.getValueAt(i, 1).toString());
                edicaoGipDTO.setCargaLevantada_faturanova(model.getValueAt(i, 2).toString());
                edicaoGipDTO.setMedidorInstalacao_faturanova(model.getValueAt(i, 3).toString());
                edicaoGipDTO.setRua_faturanova(model.getValueAt(i, 4).toString());
                edicaoGipDTO.setNumero_faturanova(model.getValueAt(i, 5).toString());
                edicaoGipDTO.setBairro_faturanova(model.getValueAt(i, 6).toString());
                edicaoGipDTO.setTipos_faturanova(model.getValueAt(i, 7).toString());
                edicaoGipDTO.setCodBarrasRed_faturanova(model.getValueAt(i, 8).toString());
                edicaoGipDTO.setUnidade_faturanova(model.getValueAt(i, 9).toString());
              

            if (!edicaoGipDTO.equals(valoresOriginais.get(i))) {
                return true; // Houve alteração
            }
        }

        return false; // Não houve alteração
    }

    private void Atualizar() {
        try {
            List<EdicaoFaturaGipDTO> valoresOriginais = getValoresOriginais();

            if (houveAlteracoes(valoresOriginais)) {
                EdicaoFaturaGipDAO edicaoGipDAO = new EdicaoFaturaGipDAO();
                for (EdicaoFaturaGipDTO edicaoGipDTO : valoresOriginais) {
                    edicaoGipDAO.atualizarCampos(edicaoGipDTO);
                }

                JOptionPane.showMessageDialog(this, "Dados editados com sucesso!");
            } else {
                JOptionPane.showMessageDialog(this, "Não houve alterações para salvar.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao editar dados: " + e.getMessage());
        }
    }
    
    // ... (restante do código)
}

